package dataobject;

public class A {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.name
     *
     * @mbggenerated Sun Dec 10 11:13:22 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a.score
     *
     * @mbggenerated Sun Dec 10 11:13:22 CST 2023
     */
    private Integer score;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.name
     *
     * @return the value of a.name
     *
     * @mbggenerated Sun Dec 10 11:13:22 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.name
     *
     * @param name the value for a.name
     *
     * @mbggenerated Sun Dec 10 11:13:22 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a.score
     *
     * @return the value of a.score
     *
     * @mbggenerated Sun Dec 10 11:13:22 CST 2023
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a.score
     *
     * @param score the value for a.score
     *
     * @mbggenerated Sun Dec 10 11:13:22 CST 2023
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}