package dataobject;

import java.util.Date;

public class MyCar {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MyCar.id
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MyCar.first_name
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MyCar.last_name
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MyCar.create_time
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MyCar.is_deleted
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    private String isDeleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MyCar.id
     *
     * @return the value of MyCar.id
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MyCar.id
     *
     * @param id the value for MyCar.id
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MyCar.first_name
     *
     * @return the value of MyCar.first_name
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MyCar.first_name
     *
     * @param firstName the value for MyCar.first_name
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName == null ? null : firstName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MyCar.last_name
     *
     * @return the value of MyCar.last_name
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MyCar.last_name
     *
     * @param lastName the value for MyCar.last_name
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public void setLastName(String lastName) {
        this.lastName = lastName == null ? null : lastName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MyCar.create_time
     *
     * @return the value of MyCar.create_time
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MyCar.create_time
     *
     * @param createTime the value for MyCar.create_time
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MyCar.is_deleted
     *
     * @return the value of MyCar.is_deleted
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MyCar.is_deleted
     *
     * @param isDeleted the value for MyCar.is_deleted
     *
     * @mbggenerated Sun Dec 10 11:16:23 CST 2023
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }
}